sonar.projectKey=audit-platform
sonar.organization=youssefouiiza
sonar.projectName=Audit Platform
sonar.sources=backend/src/main,frontend/src
sonar.java.binaries=backend/target/classes
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/.next/**
sonar.sourceEncoding=UTF-8
